"""
Django settings for db_service project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta

from dotenv import load_dotenv
from pathlib import Path

# load environment variables from .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.environ.get('APP_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django_extensions",
    'drf_spectacular',
    'rest_framework',
    'django_filters',
    'django_elasticsearch_dsl',
    'django_elasticsearch_dsl_drf_alt',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'users.apps.UsersConfig',
    'users.auth_users.apps.AuthUsersConfig',
    'news.apps.NewsConfig',
    'news.comments.apps.CommentsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': os.environ.get('POSTGRES_HOST'),
        'PORT': os.environ.get('POSTGRES_PORT'),
        'NAME': os.environ.get('POSTGRES_DB'),
        'USER': os.environ.get('POSTGRES_USER'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
    }
}

# Elasticsearch
# https://django.fun/articles/tutorials/django-rest-framework-i-elasticsearch/
# https://django-elasticsearch-dsl.readthedocs.io/en/latest/quickstart.html#install-and-configure
ELASTICSEARCH_DSL = {
    'default': {
        'hosts': f'http://{os.environ.get('ELASTIC_HOST')}:{os.environ.get('ELASTIC_PORT')}',
        'basic_auth': ('elastic', os.environ.get('ELASTIC_PASSWORD')),
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Redis
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'redis://{os.environ.get('REDIS_HOST')}:{os.environ.get('REDIS_PORT')}/{os.environ.get('REDIS_DB')}',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (  # Определяем по умолчанию классы рендеринга
        'rest_framework.renderers.JSONRenderer',  # Обмен в JSON формате
        'rest_framework.renderers.BrowsableAPIRenderer',  # Включаем API в браузере. То есть красивый интерфейс.
    ),
    'DEFAULT_PERMISSION_CLASSES': (  # Права доступа
        'rest_framework.permissions.AllowAny',  # Для всех (По умолчанию)
        # 'rest_framework.permissions.IsAuthenticated',  # Только авторизованные пользователи
    ),  # Имеет самый низкий приоритет
    'DEFAULT_AUTHENTICATION_CLASSES': (  # Способы аутентификация
        # 'rest_framework.authentication.TokenAuthentication',  # Разрешаем аутентификацию по токену
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # Разрешаем аутентификацию по JWT
        # 'rest_framework.authentication.SessionAuthentication',  # Разрешаем аутентификацию по сессии
        # 'rest_framework.authentication.BasicAuthentication',  # Тоже сессии (Эти две строчки по умолчанию)
    ),
    # 'DEFAULT_FILTER_BACKENDS': (
    #     'django_filters.rest_framework.DjangoFilterBackend',
    # ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',  # Пагинация Для всего проекта
    'PAGE_SIZE': 10,  # Размер страницы при пагинации
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'News-Aggregator DB Service API',
    'DESCRIPTION': 'News Aggregator DB Service',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,  # exclude schema from swagger-ui
    'COMPONENT_SPLIT_REQUEST': True

}

AUTH_USER_MODEL = 'users.User'

SIMPLE_JWT = {
    'ALGORITHM': 'HS256',
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=10),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

# RABBITMQ
RABBIT_SETTINGS = {
    'schema': 'amqp',
    'host': os.environ.get('RABBIT_HOST'),
    'port': os.environ.get('RABBIT_PORT'),
    'user': os.environ.get('RABBIT_USER'),
    'password': os.environ.get('RABBIT_PASSWORD'),
}

RABBITMQ_URL = (
    '{schema}://{user}:{password}@{host}:{port}/'
    .format(**RABBIT_SETTINGS)
)

# CELERY
CELERY_BROKER_URL = RABBITMQ_URL
CELERY_RESULT_BACKEND = 'rpc://'  # Положить результат в тот же брокер
CELERY_WORKER_POOL = 'prefork'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Europe/Moscow'
