# Generated by Django 5.2.5 on 2025-09-06 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_fill_sources_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='categories',
        ),
        migrations.DeleteModel(
            name='NewsCategory',
        ),
    ]
