# Generated by Django 5.2.5 on 2025-09-06 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_news_categories_delete_newscategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='news.source'),
        ),
    ]
